export const GET_LIVE_EVENT_LIST = "GET_LIVE_EVENT_LIST";
export const SET_LIVE_EVENT_LIST = "SET_LIVE_EVENT_LIST";

export const GET_EVENT_BY_ID = "GET_EVENT_BY_ID";
export const SET_EVENT_BY_ID = "SET_EVENT_BY_ID";

// export const GET_MARKET_BY_ID = "GET_MARKET_BY_ID";
export const SET_MARKET_BY_ID = "SET_MARKET_BY_ID";

export const GET_OUTCOME_LIST = "GET_OUTCOME_LIST";
// export const GET_OUTCOME_BY_ID = "GET_OUTCOME_BY_ID";
export const SET_OUTCOME_BY_ID = "SET_OUTCOME_BY_ID";

export const SET_LOADING = "SET_LOADING";

export const SET_ERROR = "SET_ERROR";

export const SET_ODDS_FORMAT = "SET_ODDS_FORMAT";

export const ADD_SELECTION = "ADD_SELECTION";
export const REMOVE_SELECTION = "REMOVE_SELECTION";
